name: Example Workflow

on:
  workflow_dispatch:

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get Date & Time
        uses: jfe726/actions-demo@main
        
      - name: List files
        shell: bash
        run: |
          ls -la .